# Site settings
title: 'WP-Shakyo | WordPress 4.0'
description:
url: https://ixkaito.github.io # the base hostname & protocol for your site
baseurl: '/wp-shakyo' # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
exclude:
  - frasco.config.js
  - gulpfile.js
  - LICENSE
  - node_modules
  - npm-debug.log
  - package.json
  - README.md
